services:
  postgres:
    image: postgres:18-alpine
    environment:
      POSTGRES_USER: snippetbox
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: snippetbox
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: