name: CI

on:
  workflow_dispatch:

  push:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v5
    
    - name: Set up Go
      uses: actions/setup-go@v6
      with:
        go-version: '1.25.2'
    
    - name: Start Docker Compose services
      run: docker compose -f ./docker-compose.yml up -d
    
    - name: Download dependencies
      run: go mod download
    
    - name: Verify dependencies
      run: go mod verify
    
    - name: Run go vet
      run: go vet ./...
    
    - name: Run go fmt check
      run: |
        if [ "$(gofmt -s -l . | wc -l)" -gt 0 ]; then
          echo "The following files are not formatted:"
          gofmt -s -l .
          exit 1
        fi
    
    - name: Build application
      run: go build -v ./...
    
    - name: Run tests
      run: go test -v ./...
    
    - name: Stop Docker Compose services
      run: docker compose -f ./docker-compose.yml down
